### ISSUE TITLE
Python 3.7 incompatibility

### ISSUE THREAD

**Issue by hippke** [rodluger/k2plr#3]
With Python 3.7, "async" became a reserved codeword. 
This crashes "api.py" in functions "light_curves" and "target_pixel_files".
Can you refactor the parameter "async" into something else. e.g. "use_async"?

**Comment by rodluger** [comment]
Changed this to "asynch" since that was DFM's patch in the base `kplr` repo. Updated the pip version (0.2.8) and the everest pip version (2.0.11) as well. Thanks!

**Comment by hippke** [comment]
works for me, thanks!
